name: bitcoin_ticker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.13.3
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Oxanium
      fonts:
        - asset: fonts/Oxanium-VariableFont_wght.ttf
    - family: CryptoIcons
      fonts:
        - asset: icons/CryptoIcons.ttf

